### ISSUE TITLE
"Image path/name" field is not visible

### ISSUE THREAD

**Issue by hmradmr24sn** [NationalSecurityAgency/qgis-kmltools-plugin#18]
When exporting to kmz the field "Image path/name" is missing. 
Expected behaviour: field for chosing column with path of image is visible

QGIS-Version
3.10.12-A Coruña
QGIS-Codeversion
75c848ffb1
Kompiliert gegen Qt
5.11.2
Laufendes Qt
5.11.2
Kompiliert mit GDAL/OGR
3.1.4
Läuft mit GDAL/OGR
3.1.4
Kompiliert mit GEOS
3.8.1-CAPI-1.13.3
Läuft mit GEOS
3.8.1-CAPI-1.13.3
Kompiliert mit SQLite
3.29.0
Läuft mit SQLite
3.29.0
PostgreSQL-Client-Version
11.5
SpatiaLite-Version
4.3.0
QWT-Version
6.1.3
QScintilla2-Version
2.10.8
Kompiliert mit PROJ
6.3.2
Läuft mit PROJ
Rel. 6.3.2, May 1st, 2020
BS-Version
Windows 10 (10.0)
Aktive Python-Erweiterungen
kmltools; 
line_profile; 
lizmap; 
nominatim_locator_filter; 
oscars-georaster-qgis-plugin; 
pluginbuilder3; 
qgis_versioning; 
QuickOSM; 
timemanager; 
track_profile_2_web; 
trail_elevation_stats; 
VoGisProfilTool; 
weissflaechenkartierung; 
processing

**Comment by hamiltoncj** [comment]
The purpose for that field is to be used in conjunction with a description popup and the image will be displayed there. The following is the documentation. Are you expecting it to do something different?

Image path/name field - This specifies the complete path to an image which will be included in to KMZ and will be displayed in the Google Earth placemark popup. As an example, if you have a directory of georeferenced images, you can run Import geotagged photos from the QGIS processing toolbox. This creates a Photo attribute which can be used for Export KMZ. Be careful that you only use small images for this purpose because all the images in the table will be copied into the KMZ and they will not be downsized.

**Comment by hmradmr24sn** [comment]
This is what I would expect it to look like (Screenshot from documentation):
![expected](https://user-images.githubusercontent.com/109689822/180204662-90ddc201-7906-4f99-9f89-229dfb224b0b.PNG)
This is how it is displayed: 
![Error](https://user-images.githubusercontent.com/109689822/180204656-0ae43716-9fd3-4a3b-ab31-13e3d07c5f2e.PNG)

**Comment by hamiltoncj** [comment]
What version of KML Tools do you have installed? It looks like you might have an old version. I have tested it in QGIS 3.10.1 and it is there. I recommend that you update your QGIS to at least 3.22 because you will be missing some KML Tools capabilities, but with QGIS 3.10.12 "Image path/name" should be there.

Make sure you are using the latest KML Tools 3.1.21.

**Comment by hamiltoncj** [comment]
Closed because of the lack of input.

**Comment by hmradmr24sn** [comment]
Installed version of KML Tools is: 3.1.6
For the moment I am bound to continue using QGIS 3.10.12-A Coruña.

**Comment by hamiltoncj** [comment]
Try installing the latest version of KML Tools (3.1.22).  There are some features that require later versions QGIS, but the path/name will be there with QGIS 3.10.12.
