### ISSUE TITLE
Legend symbology reverted/not working with latest version

### ISSUE THREAD

**Issue by timbo-barnes** [NationalSecurityAgency/qgis-kmltools-plugin#19]
After the update which added the option to keep/remove kml labels, the symbology for each feature is no longer visible in the Google Earth legend. Can this be added back as it aids a lot with map understanding.
![e5da41e8-f1a8-44c6-940d-a816a91b67f6](https://user-images.githubusercontent.com/106780193/180322164-d0c16ee5-dd41-40d9-a89d-c342b99de2df.jpg)
![8c818660-60b9-4200-8678-71dee6eda5e5](https://user-images.githubusercontent.com/106780193/180322182-dde11db8-16df-4614-a4b4-dc5c35b8d19d.jpg)

**Comment by hamiltoncj** [comment]
@timbo-barnes I uploaded KML Tools 3.1.22 to the QGIS plugin repository which fixes this problem. If you check the box "Use hidden points to display polygon labels" it has the consequence of not displaying the symbology because the symbology now becomes a hidden point. Some users want a label to be display on top of the polygon which is why this problem happened. As long as you don't check that box it will work like you want it to. Let me know if you have any other problem.

**Comment by hamiltoncj** [comment]
Closed because issue believed to be solved.
