### ISSUE TITLE
New option sugestion

### ISSUE THREAD

**Issue by Bunanai** [NationalSecurityAgency/qgis-kmltools-plugin#21]
Is it possible to consider developing a folder creation option in the KML output file based on some available field layer? It would be very helpful to separate the categorized origin data in the created file and more appearance configurations into Google Earth or other destination apps.

**Comment by hamiltoncj** [comment]
One of the purposes of KML Tools was to have an alternate way to import KMLs into QGIS and it specifically avoided creating folders because complex KMLs/KMZs with complex folder structures would tend to crash QGIS or be incredibly slow on import. One of the purposes was to only create one point layer, one line layer, and one polygon layer. I kept the folder structure information in an attribute for reference. If you import the KML using the standard QGIS importer it will keep the folder structure for you. Is there any reason you can't  do that? You can just drag and drop your KML onto the QGIS desktop. I don't think I want to replicate the embedded KML importer that is already in QGIS.

**Comment by Bunanai** [comment]
You´re perfectly right as you can manipulate data with extreme flexibility in QGIS, such filter, selection tools, SQL, etc.  In a matter of fact, the idea is to create folders when creating a KML "output" file, so when exporting data from QGIS, not importing to QGIS. Sorry if I did not express myself well.

**Comment by hamiltoncj** [comment]
Sorry to have misunderstood your suggestion. This is possible, but would take some work. I probably can't get to this right away, but I think it is a good suggestion and will try to implement it.

**Comment by hamiltoncj** [comment]
I just put out a new update (3.1.25) that I believe implements this request. In the Advanced Parameters there is an option to choose a field to create categorized output KML subfolders. Let me know if that is what you wanted.

**Comment by Bunanai** [comment]
Hi, good news. I have already tested and worked fine. Thank you. I believe it will help a huge number of users. But I couldn´t find the option on the processing windows. It will be some future implementation or I didn´t look it up well?
 Congratulations again for this work.

**Comment by hamiltoncj** [comment]
@Bunanai 
It is there, but I put it in the Advanced  Parameters that you will need to expand to see. You select "Field to create categorized KML subfolders". 

In the Processing Toolbox you select it from "KML tools->Vector conversion->Export KMZ". You need to be using one of the more recent versions of QGIS. It is also on the toolbar and in the QGIS Plugins menu.

**Comment by hamiltoncj** [comment]
I believe this request has been fulfilled so I am closing the issue.

**Comment by Bunanai** [comment]
Hi,
Sorry for my later answer. It works very fine. I found out the option at processing mode.
Thank you very much. I believe it will help many people.
Congratulations.
