### ISSUE TITLE
png-files overwritten and in wrong place?

### ISSUE THREAD

**Issue by 9ls1** [NationalSecurityAgency/qgis-kmltools-plugin#27]
Thanks for a very nice plugin. I'm facing a problem with a kmz-file containing appr. 990 png-files in 35 sub-directories within the kmz-file. There are only 43 unique png filenames (the same filename is repeated in the different sub-folders).
I want to open the kmz (kml) file in QGIS and get all the png-files opened and shown at their correct location. Is that possible to do with this plugin? The kmz-file is zipped and attached.
[Hardangervidda_v6.zip](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/files/10943085/Hardangervidda_v6.zip)

**Comment by hamiltoncj** [comment]
I have not had the time to really look at this yet, but one comment is that based on what I see as images would be much better if they were polygons. One challenge I am facing is that I am no longer allowed to do further development only bug fixes. This can probably be considered a bug for overwriting files. If I have a chance I will look at it more next week and if it is an easy fix, make the change, but I highly recommend making these polygons rather than images.

**Comment by 9ls1** [comment]
Thanks for replying. I'm not creating the kmz-file my self. I just receive them in this way (with png-images and not polygons). The problem is that more or less all the 990 files are overwritten in the process resulting in 43 geotiff-files placed upon each other due to the lack of correct georeferencing.
It seems to me that the coordinates of each png are in the doc.kml-file and it should be possible to create a script that creates world-files for each of the png-files. I may try to find time my self to look into it later this spring if you don't get the chance.

**Comment by hamiltoncj** [comment]
I made a change so that it will not overwrite the images. It is not an elegant solution but it works. When you have so many images like the file you shared, I recommend that you uncheck the box to automatically load the images. I found that too many can crash QGIS. If you just want to visualize the results I recommend that you run the gdal merge algorithm on the directory of these images. That way it will render one image combining all the images together.

**Comment by 9ls1** [comment]
Thanks for updating the plugin! It now works like  a charm in my case. And thanks for the gdal_merge tip. I made a script for merging all the resulting tifs from the plugin (I have to do it for X files at the time, gdal_merge is not merging 992 files in one operation).

**Comment by hamiltoncj** [comment]
I think part of the problem is QGIS accesses gdal_merge by putting all the image file names on the command sting. If you are comfortable with running gdal_merge from the OSGeo4W Shell you can do something like

```
dir /b *.tif > files.txt
gdal_merge -co "TILED=YES" -v --optfile files.txt -o merged_output_image.txt
```

I have done this with thousands of images and it works well. I like using the tiled flag. If the output image becomes exceptionally large you might need -co "BIGTIFF=YES". You wont need it with this example.

**Comment by 9ls1** [comment]
👌 Worked perfectly with a bat-file containing (changed the typo(?) txt to tif and added /S to get all tif-files in the subfolders):
```
dir /S /b *.tif > files.txt
call C:\OSGeo4W\apps\Python39\Scripts\gdal_merge.bat -co "TILED=YES" -v --optfile files.txt -o merged_output_image.tif
```
Once again, thanks a lot for your effort changing the plugin and your gdal_merge tip. Most appreciated!
