### ISSUE TITLE
Language issues, when installing it from the plugin menu and from zip file , its always in korean.

### ISSUE THREAD

**Issue by Faster22** [NationalSecurityAgency/qgis-kmltools-plugin#29]
Everytime i install this its in Korean.

![image](https://github.com/NationalSecurityAgency/qgis-kmltools-plugin/assets/58865387/d3e92453-5160-442e-8037-25ab297393e7)

**Comment by hamiltoncj** [comment]
What you are showing has nothing to do with KML Tools and since it is not readable to me I don't know what it is. The QGIS language settings are found under "Settings->Options" and then under the General tab. Other than that I cannot help with general QGIS questions - only ones related to my plugins. Here is where you can get general QGIS support.

https://qgis.org/en/site/forusers/support.html
